//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
#include "ECDiffusionControlTwoReactionTestApp.h"
#include "ECDiffusionControlTwoReactionApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template <>
InputParameters
validParams<ECDiffusionControlTwoReactionTestApp>()
{
  InputParameters params = validParams<ECDiffusionControlTwoReactionApp>();
  return params;
}

ECDiffusionControlTwoReactionTestApp::ECDiffusionControlTwoReactionTestApp(InputParameters parameters) : MooseApp(parameters)
{
  ECDiffusionControlTwoReactionTestApp::registerAll(
      _factory, _action_factory, _syntax, getParam<bool>("allow_test_objects"));
}

ECDiffusionControlTwoReactionTestApp::~ECDiffusionControlTwoReactionTestApp() {}

void
ECDiffusionControlTwoReactionTestApp::registerAll(Factory & f, ActionFactory & af, Syntax & s, bool use_test_objs)
{
  ECDiffusionControlTwoReactionApp::registerAll(f, af, s);
  if (use_test_objs)
  {
    Registry::registerObjectsTo(f, {"ECDiffusionControlTwoReactionTestApp"});
    Registry::registerActionsTo(af, {"ECDiffusionControlTwoReactionTestApp"});
  }
}

void
ECDiffusionControlTwoReactionTestApp::registerApps()
{
  registerApp(ECDiffusionControlTwoReactionApp);
  registerApp(ECDiffusionControlTwoReactionTestApp);
}

/***************************************************************************************************
 *********************** Dynamic Library Entry Points - DO NOT MODIFY ******************************
 **************************************************************************************************/
// External entry point for dynamic application loading
extern "C" void
ECDiffusionControlTwoReactionTestApp__registerAll(Factory & f, ActionFactory & af, Syntax & s)
{
  ECDiffusionControlTwoReactionTestApp::registerAll(f, af, s);
}
extern "C" void
ECDiffusionControlTwoReactionTestApp__registerApps()
{
  ECDiffusionControlTwoReactionTestApp::registerApps();
}
